/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Characters */
        get: operations["list_characters_api_characters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/meta/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Character Options
         * @description 筛选项元数据（职阶/体系/来源列表）。注意：必须在 /{character_id} 之前声明。
         */
        get: operations["character_options_api_characters_meta_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character */
        get: operations["get_character_api_characters__character_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Character Relationships */
        get: operations["character_relationships_api_characters__character_id__relationships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/family": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Character Family */
        get: operations["character_family_api_characters__character_id__family_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/ego": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Character Ego */
        get: operations["character_ego_api_characters__character_id__ego_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Relationships */
        get: operations["list_relationships_api_relationships_get"];
        put?: never;
        /**
         * Submit Relationship
         * @description 众包提交关系（进入审核队列）。
         */
        post: operations["submit_relationship_api_relationships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Pending */
        get: operations["review_pending_api_review_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{relationship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Decide */
        post: operations["review_decide_api_review__relationship_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Batch
         * @description 批量审核：{"<id>": "approve"|"reject", ...}
         */
        post: operations["review_batch_api_review_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clusters */
        get: operations["get_clusters_api_graph_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Graph */
        post: operations["refresh_graph_api_graph_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Path
         * @description from/to 为角色 ID（如 c1、c496）。
         */
        get: operations["find_path_api_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily Game */
        get: operations["daily_game_api_games_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/daily/guess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Daily Guess */
        post: operations["daily_guess_api_games_daily_guess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/daily/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Daily Reveal */
        post: operations["daily_reveal_api_games_daily_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ai_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/nlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nlq */
        post: operations["nlq_api_ai_nlq_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/whatif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Whatif */
        post: operations["whatif_api_ai_whatif_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest */
        get: operations["suggest_api_ai_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Research
         * @description gpt-luna-5.6 联网研究（需配置 LUNA_*）。
         */
        post: operations["research_api_ai_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/graphml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Graphml */
        get: operations["export_graphml_api_export_graphml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_api_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Nodes */
        get: operations["export_nodes_api_export_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/img": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Img Proxy */
        get: operations["img_proxy_api_img_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskCitation */
        AskCitation: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Relation
             * @default
             */
            relation: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["AskCitation"][];
            subgraph?: components["schemas"]["GraphDTO"] | null;
            /**
             * Engine
             * @default graph
             */
            engine: string;
        };
        /** CharacterDTO */
        CharacterDTO: {
            /** Id */
            id: string;
            /** Wikiid */
            wikiId: number;
            /** Name */
            name: string;
            /**
             * Aliases
             * @default []
             */
            aliases: string[];
            /**
             * Classname
             * @default
             */
            className: string;
            /**
             * Prototype
             * @default
             */
            prototype: string;
            /** Mythology */
            mythology?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Mythologybackground
             * @default
             */
            mythologyBackground: string;
            /**
             * Alignment
             * @default
             */
            alignment: string;
            /**
             * Gender
             * @default
             */
            gender: string;
            /**
             * Imageurl
             * @default
             */
            imageUrl: string;
            /**
             * Detailurl
             * @default
             */
            detailUrl: string;
            /**
             * Source
             * @default fgo
             */
            source: string;
            /**
             * Extra
             * @default {}
             */
            extra: {
                [key: string]: unknown;
            };
            /**
             * Degree
             * @default 0
             */
            degree: number;
        };
        /** CharacterListItem */
        CharacterListItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Classname
             * @default
             */
            className: string;
            /** Mythology */
            mythology?: string | null;
            /**
             * Imageurl
             * @default
             */
            imageUrl: string;
            /**
             * Degree
             * @default 0
             */
            degree: number;
            /**
             * Hasrelation
             * @default false
             */
            hasRelation: boolean;
        };
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "low" | "medium" | "high" | "verified";
        /** DailyGuess */
        DailyGuess: {
            /** Guess */
            guess: string;
        };
        /** GraphDTO */
        GraphDTO: {
            /** Nodes */
            nodes: components["schemas"]["GraphNodeDTO"][];
            /** Links */
            links: components["schemas"]["GraphLinkDTO"][];
            /**
             * Meta
             * @default {}
             */
            meta: {
                [key: string]: unknown;
            };
        };
        /** GraphLinkDTO */
        GraphLinkDTO: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            type: components["schemas"]["RelationshipType"];
            /**
             * Directed
             * @default true
             */
            directed: boolean;
            /**
             * Confidence
             * @default verified
             */
            confidence: string;
        };
        /** GraphNodeDTO */
        GraphNodeDTO: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @default character
             */
            kind: string;
            /** Mythology */
            mythology?: string | null;
            /**
             * Classname
             * @default
             */
            className: string;
            /**
             * Imageurl
             * @default
             */
            imageUrl: string;
            /**
             * Degree
             * @default 0
             */
            degree: number;
            /**
             * Wikiid
             * @default 0
             */
            wikiId: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NlqRequest */
        NlqRequest: {
            /** Query */
            query: string;
        };
        /** PathDTO */
        PathDTO: {
            /** Found */
            found: boolean;
            /**
             * Distance
             * @default 0
             */
            distance: number;
            /**
             * Nodes
             * @default []
             */
            nodes: components["schemas"]["GraphNodeDTO"][];
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["PathStepDTO"][];
        };
        /** PathStepDTO */
        PathStepDTO: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            type: components["schemas"]["RelationshipType"];
            /**
             * Label
             * @default
             */
            label: string;
        };
        /**
         * RelationOrigin
         * @enum {string}
         */
        RelationOrigin: "manual" | "llm" | "user" | "wiki";
        /** RelationshipDTO */
        RelationshipDTO: {
            /** Id */
            id: number;
            /** Sourceid */
            sourceId: string;
            /** Targetid */
            targetId: string;
            type: components["schemas"]["RelationshipType"];
            /**
             * Directed
             * @default true
             */
            directed: boolean;
            confidence: components["schemas"]["Confidence"];
            /**
             * Evidence
             * @default
             */
            evidence: string;
            origin: components["schemas"]["RelationOrigin"];
            /** @default approved */
            status: components["schemas"]["ReviewStatus"];
            /**
             * Sourcename
             * @default
             */
            sourceName: string;
            /**
             * Targetname
             * @default
             */
            targetName: string;
        };
        /**
         * RelationshipSubmit
         * @description 众包关系提交（进入审核队列）。
         */
        RelationshipSubmit: {
            /** Sourceid */
            sourceId: string;
            /** Targetid */
            targetId: string;
            type: components["schemas"]["RelationshipType"];
            /** Evidence */
            evidence: string;
            /**
             * Contributor
             * @default 匿名
             */
            contributor: string;
        };
        /**
         * RelationshipType
         * @description 关系类型（存储层只用规范方向，逆关系在入库时归一化）。
         * @enum {string}
         */
        RelationshipType: "PARENT_OF" | "SIBLING_OF" | "SPOUSE_OF" | "LOVER_OF" | "MASTER_OF" | "ALLY_OF" | "ENEMY_OF" | "FOUGHT_WITH" | "MENTOR_OF" | "PROTOTYPE_IS" | "GENDER_SWAP" | "DERIVED_FROM" | "COMPOSITE_OF" | "BELONGS_TO";
        /** ReviewDecision */
        ReviewDecision: {
            /** Action */
            action: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "approved" | "pending" | "rejected";
        /** SearchHitDTO */
        SearchHitDTO: {
            character: components["schemas"]["CharacterListItem"];
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Matchedon
             * @default
             */
            matchedOn: string;
        };
        /** SearchResponseDTO */
        SearchResponseDTO: {
            /** Query */
            query: string;
            /**
             * Semantic
             * @default false
             */
            semantic: boolean;
            /**
             * Hits
             * @default []
             */
            hits: components["schemas"]["SearchHitDTO"][];
        };
        /** StatsDTO */
        StatsDTO: {
            /** Characters */
            characters: number;
            /** Relationships */
            relationships: number;
            /** Approved */
            approved: number;
            /** Pending */
            pending: number;
            /** Enriched */
            enriched: number;
            /** Missingmythology */
            missingMythology: number;
            /** Missingdescription */
            missingDescription: number;
            /** Orphannodes */
            orphanNodes: number;
            /**
             * Relationdist
             * @default {}
             */
            relationDist: {
                [key: string]: number;
            };
            /**
             * Confidencedist
             * @default {}
             */
            confidenceDist: {
                [key: string]: number;
            };
            /**
             * Mythologydist
             * @default {}
             */
            mythologyDist: {
                [key: string]: number;
            };
            /**
             * Classdist
             * @default {}
             */
            classDist: {
                [key: string]: number;
            };
            /**
             * Origindist
             * @default {}
             */
            originDist: {
                [key: string]: number;
            };
        };
        /** SuggestionDTO */
        SuggestionDTO: {
            /** Sourceid */
            sourceId: string;
            /** Targetid */
            targetId: string;
            /**
             * Commonneighbors
             * @default []
             */
            commonNeighbors: string[];
            /**
             * Samemythology
             * @default false
             */
            sameMythology: boolean;
            /**
             * Score
             * @default 0
             */
            score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            /** Aid */
            aId: string;
            /** Bid */
            bId: string;
        };
        /** WhatIfResponse */
        WhatIfResponse: {
            /** Narrative */
            narrative: string;
            /**
             * Engine
             * @default graph
             */
            engine: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_characters_api_characters_get: {
        parameters: {
            query?: {
                mythology?: string | null;
                className?: string | null;
                gender?: string | null;
                hasRelation?: boolean | null;
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    character_options_api_characters_meta_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_character_api_characters__character_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    character_relationships_api_characters__character_id__relationships_get: {
        parameters: {
            query?: {
                includePending?: boolean;
            };
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    character_family_api_characters__character_id__family_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    character_ego_api_characters__character_id__ego_get: {
        parameters: {
            query?: {
                hops?: number;
            };
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_relationships_api_relationships_get: {
        parameters: {
            query?: {
                status?: string | null;
                origin?: string | null;
                type?: string | null;
                confidence?: string | null;
                characterId?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_relationship_api_relationships_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_pending_api_review_pending_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-review-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_decide_api_review__relationship_id__post: {
        parameters: {
            query?: never;
            header?: {
                "x-review-token"?: string | null;
            };
            path: {
                relationship_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_batch_api_review_batch_post: {
        parameters: {
            query?: never;
            header?: {
                "x-review-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_graph_get: {
        parameters: {
            query?: {
                mythologies?: string[] | null;
                types?: string[] | null;
                classes?: string[] | null;
                gender?: string | null;
                search?: string | null;
                onlyRelated?: boolean;
                includeMythNodes?: boolean;
                egoCenter?: string | null;
                egoHops?: number;
                maxWikiId?: number | null;
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clusters_api_graph_clusters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_graph_api_graph_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    find_path_api_paths_get: {
        parameters: {
            query: {
                from_id: string;
                to_id: string;
                maxHops?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsDTO"];
                };
            };
        };
    };
    daily_game_api_games_daily_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    daily_guess_api_games_daily_guess_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyGuess"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_reveal_api_games_daily_reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ask_api_ai_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nlq_api_ai_nlq_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NlqRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatif_api_ai_whatif_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatIfResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_api_ai_suggest_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_api_ai_research_post: {
        parameters: {
            query: {
                question: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_graphml_api_export_graphml_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    export_csv_api_export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    export_nodes_api_export_nodes_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    img_proxy_api_img_get: {
        parameters: {
            query: {
                url: string;
                size?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
